# 网站的基本信息
site:
  tab: Eser Sevinç # 浏览器标签栏上显示的文本
  title: Eser Sevinç'in kişisel blogu. # 网站的标题
  description: Yazılım sektöründe; İş Analizi, Proje Yönetimi, Ekip Yönetimi ve Liderlik gibi konular üzerine bilgi birikimi. # 网站的描述，用于SEO等
  language: en # 网站的语言，例如 "en" 是英文
  favicon: /favicon.ico # Tarayıcı sekmelerinde ve diğer yerlerde kullanılan web sitesinin simgesi
  theme: # 更多主题 https://daisyui.com/docs/themes/
    light: light # 主题的浅色模式
    dark: dim # 主题的深色模式
    code: dracula # 代码块的主题 https://shiki.style/themes
  date_format: ddd MMM DD YYYY # 日期格式设置，支持自定义格式
  blog: # 博客相关配置
    pageSize: 8 # 每页显示的文章数量
  menu: # 菜单配置
    - id: home # 菜单项的唯一标识符
      text: Anasayfa # 菜单项显示的文本
      href: / # 菜单项链接的地址
      svg: "material-symbols:home-outline-rounded"
      target: _self
    - id: about
      text: Hakkımda
      href: /about
      svg: "material-symbols:info-outline-rounded"
      target: _self
    - id: blog
      text: Blog
      href: /blog
      svg: "material-symbols:book-2-outline-rounded"
      target: _self
      subItems:
        - id: all
          text: Tüm yazılar
          href: /blog
          svg: "material-symbols:ink-pen-outline-rounded"
          target: _self
        - id: tech
          text: İş ile ilgili
          href: /blog/category/work
          svg: "material-symbols:deployed-code-outline"
          target: _self
        - id: life
          text: Kişisel yaşam
          href: /blog/category/life
          svg: "material-symbols:earthquake-rounded"
          target: _self
        # 子菜单项配置
    - id: project
      text: Projeler
      href: /project
      svg: "material-symbols:code-blocks-outline"
      target: _self
    - id: friend
      text: Blogroll
      href: /friend
      svg: "material-symbols:supervisor-account-outline-rounded"
      target: _self
    - id: contact
      text: İletişim
      href: /contact
      svg: "material-symbols:attach-email-outline-rounded"

# 用户的个人信息
user:
  name: Eser Sevinç # 用户名
  site: "https://esersevinc.com.tr" # 用户的网站链接
  avatar: /ES.png # 用户头像路径
  sidebar: # 侧边栏配置
    social:
      - href: "https://buymeacoffee.com/esersevinc" # 链接
        ariaLabel: Support my work # 图标的可访问性标签
        title: Bir kahve ısmarla # 图标的悬浮标题
        svg: "ri:cup-line"
      - href: "https://github.com/Eser360"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
      - href: "https://mastodon.social/@esersevinc"
        ariaLabel: Mastodon
        title: Mastodon
        svg: "ri:mastodon-line"
      - href: "https://www.linkedin.com/in/esersevinc/"
        ariaLabel: Linkedin
        title: Linkedin
        svg: "ri:linkedin-line"
  footer:
    social:
      - href: "https://buymeacoffee.com/esersevinc" # 链接
        ariaLabel: Support my work # 图标的可访问性标签
        title: Bir kahve ısmarla # 图标的悬浮标题
        svg: "ri:cup-line"
      - href: "https://github.com/Eser360"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
      - href: "https://mastodon.social/@esersevinc"
        ariaLabel: Mastodon
        title: Mastodon
        svg: "ri:mastodon-line"
      - href: "https://www.linkedin.com/in/esersevinc/"
        ariaLabel: Linkedin
        title: Linkedin
        svg: "ri:linkedin-line"
